import { useState, useEffect } from 'react'
import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Container from '../components/Container'
import music from '../components/data/music'


export default function Home() {


  const [slide, setSlide] = useState(false)
  const [index, setIndex] = useState(0)
  const [data, setData] = useState(music[0])

  const handleSlide = () => {
    setSlide(!slide)
  }

  const handleIndex = arg => {
    if(arg < 0){
      return setIndex(music.length - 1)
    }else if(arg > music.length - 1){
      setIndex(0)
    }else{
      setIndex(arg)
    }
  }

  useEffect(() => {
    setData(music[index])
  }, [index])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`App ${slide ? 'active' : ''}`}>
        <Sidebar 
          song={data} 
          handleSlide={handleSlide} 
          slide={slide} 
          handleIndex={handleIndex}
          index={index}
        />
        <Container songs={music} />
      </div>
    </>
  )
}
